#!/bin/bash
# Claw3D Setup Script for MONI AI
# Usage: bash scripts/setup-claw3d.sh
#
# Installs and configures Claw3D — the 3D visual workspace
# that connects to your OpenClaw Gateway so you can watch
# MONI, FALAH, AURIX, and BAYAN agents work in real time.

set -e

echo "🏢 Claw3D Setup for MONI AI"
echo "============================"
echo ""

CLAW3D_DIR="$(cd "$(dirname "$0")/.." && pwd)/claw3d"
GATEWAY_URL="${GATEWAY_URL:-ws://localhost:18789}"
STUDIO_PORT="${STUDIO_PORT:-3000}"

# ── Step 1: Check prerequisites ──────────────────────────────

echo "Checking prerequisites..."

if ! command -v node &> /dev/null; then
    echo "❌ Node.js not found. Install Node.js 20+ first."
    exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo "❌ Node.js 20+ required (found v$(node -v))"
    exit 1
fi
echo "  ✅ Node.js $(node -v)"

if ! command -v npm &> /dev/null; then
    echo "❌ npm not found."
    exit 1
fi
echo "  ✅ npm $(npm -v)"

if ! command -v openclaw &> /dev/null; then
    echo "⚠️  OpenClaw not found. Claw3D needs a running gateway to connect to."
    echo "   Install: npm install -g openclaw@latest"
fi

# ── Step 2: Initialize submodule if needed ───────────────────

if [ ! -f "$CLAW3D_DIR/README.md" ]; then
    echo ""
    echo "Initializing Claw3D submodule..."
    cd "$(dirname "$0")/.."
    git submodule update --init --recursive claw3d
fi

echo "  ✅ Claw3D source ready"

# ── Step 3: Install dependencies ─────────────────────────────

echo ""
echo "Installing Claw3D dependencies..."
cd "$CLAW3D_DIR"

if [ -f "package.json" ]; then
    npm install --production 2>/dev/null || npm install
    echo "  ✅ Dependencies installed"
else
    echo "  ℹ️  No package.json found — Claw3D may be documentation-only at this stage."
    echo "     When source code is released, re-run this script to install dependencies."
fi

# ── Step 4: Configure environment ────────────────────────────

echo ""
echo "Configuring environment..."

if [ -f ".env.example" ] && [ ! -f ".env" ]; then
    cp .env.example .env
    echo "  ✅ .env created from .env.example"
fi

# Create .env if it doesn't exist
if [ ! -f ".env" ]; then
    cat > .env << EOF
# Claw3D Studio Configuration
# Generated by MONI AI setup script

# OpenClaw Gateway connection
GATEWAY_URL=${GATEWAY_URL}

# Studio server port
PORT=${STUDIO_PORT}

# Studio access token (set this if exposing Studio on a network)
# STUDIO_ACCESS_TOKEN=your-secure-token-here
EOF
    echo "  ✅ .env created with defaults"
else
    echo "  ℹ️  .env already exists, skipping"
fi

# ── Step 5: Summary ──────────────────────────────────────────

echo ""
echo "============================"
echo "🎉 Claw3D setup complete!"
echo ""
echo "Configuration:"
echo "  Gateway URL:  $GATEWAY_URL"
echo "  Studio Port:  $STUDIO_PORT"
echo "  Directory:    $CLAW3D_DIR"
echo ""
echo "Next steps:"
echo "  1. Make sure your OpenClaw gateway is running:"
echo "     openclaw gateway start"
echo ""
echo "  2. Start Claw3D Studio:"
echo "     cd claw3d && npm run dev"
echo ""
echo "  3. Open http://localhost:${STUDIO_PORT}"
echo "     Configure your gateway token in the Studio UI"
echo ""
echo "  4. Watch MONI, FALAH, AURIX & BAYAN in the 3D office!"
echo ""
echo "Tip: For remote gateway, set GATEWAY_URL before running:"
echo "  GATEWAY_URL=wss://your-server.ts.net bash scripts/setup-claw3d.sh"
